### ISSUE TITLE
Plan for Blog

### ISSUE THREAD

**Issue by JessyRiordan** [JessyRiordan/TIY-BlogSite#9]
* [ ] Make a plan re #8  
* [ ] **Picture**
  * [ ] Top of main page
* [ ] **Navigation Bar**
  * [ ] Home
  * [ ] Contact
  * [ ] Github Profile (thanks for the idea @MStaehling)
  * [ ] About
* [ ] **Content**
  * [ ] Blog - more to come

**Comment by JessyRiordan** [comment]
https://github.com/TheIronYard--Orlando/2015--SUMMER--FEE/issues/214

**Comment by JessyRiordan** [comment]
https://github.com/TheIronYard--Orlando/2015--SUMMER--FEE/issues/214

**Comment by al-the-x** [comment]
There might be a bit more to this than that...

**Comment by al-the-x** [comment]
I would break the site down into pages and horizontal sections:

* Home Page:
  * Primary Header (Picture)
  * Navigation Header
  * Blog Post List
  * Pagination
  * Footer
* Single Post Page:
  * Primary Header
  * Navigation Header
  * Blog Post
  * Footer
* Static Page:
  * Primary Header
  * Navigation Header
  * Primary Content
  * Footer

Then, I would refactor the plan to extract the common items... once I was sure that they were common:

* Overall Theme:
  * Primary Header
  * Navigation Header
  * Footer

Then I would start adding details to the sections:

* Overall Theme:
  * Primary Header
    * Hi-res background image
    * Floating icon, vertically centered?
  * Navigation Header
    * What goes in here?
    * Fix to top of viewport when scrolling down? HOW?
    * Links right-aligned, spacing?
  * . . .

So on and so forth. Write it down and execute.
